import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { GapAnalysisResult } from './GapAnalysisReport';

export const exportGapAnalysisToPDF = (data: GapAnalysisResult, organizationName: string) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString('en-GB');

    // Header
    doc.setFontSize(22);
    doc.setTextColor(20, 40, 100);
    doc.text('Compliance Gap Analysis Report', 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Organisation: ${organizationName}`, 14, 30);
    doc.text(`Date: ${date}`, 14, 35);

    // Summary Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text('Executive Summary', 14, 50);

    doc.setFontSize(11);
    const splitSummary = doc.splitTextToSize(data.aiSummary, 180);
    doc.text(splitSummary, 14, 58);

    // Stats Table
    (doc as any).autoTable({
        startY: 75,
        head: [['Metric', 'Value']],
        body: [
            ['Total Staff', data.totalEmployees],
            ['Fully Compliant', data.compliantCount],
            ['Compliance Rate', `${Math.round((data.compliantCount / data.totalEmployees) * 100)}%`],
            ['Risk Score (0-100)', data.riskScore]
        ],
        theme: 'striped',
        headStyles: { fillColor: [41, 128, 185] }
    });

    // Critical Gaps
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(16);
    doc.text('Critical Gaps Identified', 14, finalY);

    doc.setFontSize(11);
    let gapY = finalY + 8;
    data.criticalGaps.forEach((gap, index) => {
        doc.text(`• ${gap}`, 14, gapY);
        gapY += 7;
    });

    // Recommendations
    doc.setFontSize(16);
    doc.text('Recommendations', 14, gapY + 10);

    doc.setFontSize(11);
    let recY = gapY + 18;
    data.recommendations.forEach((rec, index) => {
        const splitRec = doc.splitTextToSize(`${index + 1}. ${rec}`, 180);
        doc.text(splitRec, 14, recY);
        recY += (splitRec.length * 7);
    });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text('Generated by NovumFlow AI Compliance Intelligence', 14, 285);

    doc.save(`Compliance_Report_${organizationName.replace(/\s+/g, '_')}_${date}.pdf`);
};
