#!/bin/bash

# Generated by Gemini for NovumFlow Deployment

# 1. Generate a strong random secret
WEBHOOK_SECRET=$(openssl rand -hex 32)
echo "Generated Webhook Secret: $WEBHOOK_SECRET"

# 2. Set secrets for CareFlow AI (Project: kvtdyttgthbeomyvtmbj)
echo "Setting secrets for CareFlow AI..."
cd careflow-ai
supabase secrets set NOVUMFLOW_WEBHOOK_SECRET=$WEBHOOK_SECRET --project-ref kvtdyttgthbeomyvtmbj
cd ..

# 3. Set secrets for HR Recruitment Platform (Project: niikshfoecitimepiifo)
echo "Setting secrets for HR Recruitment Platform..."
cd hr-recruitment-platform
supabase secrets set CAREFLOW_WEBHOOK_SECRET=$WEBHOOK_SECRET --project-ref niikshfoecitimepiifo
supabase secrets set CAREFLOW_SYNC_EMPLOYEE_URL=https://kvtdyttgthbeomyvtmbj.supabase.co/functions/v1/sync_employee --project-ref niikshfoecitimepiifo

# Note: GOOGLE_API_KEY must be set manually by the user as I don't have it.
echo ""
echo "✅ Webhook secrets and URLs configured!"
echo "⚠️  REMINDER: You still need to set GOOGLE_API_KEY for the HR platform if you haven't already."
echo "   Run: cd hr-recruitment-platform && supabase secrets set GOOGLE_API_KEY=your_key_here --project-ref niikshfoecitimepiifo"
